name: Deploy App
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Cache
        uses: actions/cache@v3.3.2
        with:
          path: node_modules
          key: ${{ runner.os }}-marble-solitaire-app-build-${{ github.run_id }}
          restore-keys: ${{ runner.os }}-marble-solitaire-app-build-
      - name: Install Dependencies
        run: npm install --legacy-peer-deps
      - name: Build Static Site
        run: npm run build
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
      - name: Deploy to S3 Bucket
        run: npm run deploy
